metadata:
  name: lulc-classification-modis

  description: Reproducible Land Use and Land Cover classification for 
    MOD13Q1 Data Cube, using the SITS analytical R package.
  
  licenses:
    code: MIT

    data: MIT

    text: MIT

  author: Felipe Menino
  author_email: felipe.carlos@inpe.br

  creation: 2021-08-06T10:08:04

config:
  working_directories:
  - ./

  datasources:
    foo:
      pattern: /foo/*
      action: include
secrets: [BDC_ACCESS_KEY]
