metadata:
    name: parallel-reproduction

    description: Reproducible Temporal Watermask for Mato Grosso State

    licenses:
        code: MIT

        data: MIT

        text: MIT

    author: Felipe Menino
    author_email: felipe.carlos@inpe.br

    creation: 2021-09-01T04:08:04

config:
    working_directories:
        - ./

    datasources:
        foo:
            pattern: /foo/*
            action: include
secrets: [ BDC_ACCESS_KEY ]
