metadata:
  name: lulc-classification-lc8

  description: Reproducible Land Use and Land Cover classification for 
  Landsat-8/OLI Data Cube, using the SITS analytical R package.

  licenses:
    code: MIT

    data: MIT

    text: MIT

  author: Felipe Menino
  author_email: felipe.carlos@inpe.br

  creation: 2021-09-03T17:14:35

config:
  working_directories:
  - ./

  datasources:
    foo:
      pattern: /foo/*
      action: include
secrets: [BDC_ACCESS_KEY]
