metadata:
  name: local-cube

  description: Usage example of the bdcrrm-api for research file management.

  licenses:
    code: MIT

    data: MIT

    text: MIT

  author: Felipe Menino
  author_email: felipe.carlos@inpe.br

  creation: 2021-09-07T00:08:26

config:
  working_directories:
  - ./

  datasources:
    lc8_amazon_datasource:
      pattern: '*data/raw_data/L8_Amazon/*/*.tif'
      action: include
secrets: []

