metadata:
  name: cook

  description: Example of reproducible project using Python programming language and bdcrrm-api.

  licenses:
    code: MIT
    data: MIT
    text: MIT

  author: Felipe Menino
  author_email: felipe.carlos@inpe.br

  creation: 2021-08-04T00:06:40.747788

config:
  working_directories:
    - ./

  datasources:
    foo:
      pattern: /foo/*
      action: include # or exclude

secrets:
  - MySecret
