metadata:
  name: lulc-classification-cbers

  description: Reproducible Land Use and Land Cover classification for 
    CBERS-4/AWFI Data Cube, using the SITS analytical R package.

  licenses:
    code: MIT

    data: MIT

    text: MIT

  author: Felipe Menino
  author_email: felipe.carlos@inpe.br

  creation: 2021-08-06T03:08:35

config:
  working_directories:
  - ./

  datasources:
    foo:
      pattern: /foo/*
      action: include
secrets: [BDC_ACCESS_KEY]
